In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import pickle
from collections import defaultdict
from sklearn.model_selection import train_test_split
from numpy.core.records import array
from keras.models import load_model
import time


In [3]:
with open('/content/grids_agent3_dim10_count1000.pkl', "rb") as f:
    dict = pickle.load(f)

X = dict['KnowledgeGrid']
X_PS = dict['KnowledgeGridPS']
Y = dict['action']
position_dict = dict['position']
index_dict = dict['Index']
data_count = len(Y)
gridSize = len(X[0][0])
maze_dict = dict['maze']
AstartTime_dict = dict['AstarTime']

In [4]:
# Reshape position list into array
for i in range(data_count):
  position_dict[i] = np.reshape(position_dict[i], 1*2)

In [5]:
print(gridSize)
print(data_count)
print(X[0])
print(X_PS[0])
print(position_dict[0])
print(len(maze_dict))
print((maze_dict[0]))
print((AstartTime_dict[0]))
print(len(AstartTime_dict))
print((AstartTime_dict))
print(X[0].shape[0])

10
34606
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[ 0 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]
[0 0]
1000
[[0, 0, 0, 1, 0, 1, 0, 1, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 1, 0, 1, 0, 0, 0, 1, 1, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 1, 0, 0, 0, 1, 0, 0, 1, 0], [1, 0, 1, 0, 0, 1, 0, 1, 0, 0], [0, 0, 1, 0, 1, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 1, 1, 1, 0, 0], [0, 1, 0, 1, 0, 0, 0, 1, 1, 0], [0, 0, 0, 0, 1, 1, 1, 0, 1, 0]]
0.0
1000
[0.0, 0.0, 0.0010001659393310547, 0.0010728836059570312, 0.0, 0.0009965896606445312, 0.0

Add position to knowledge grid

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, shuffle=False)
train_length = len(Y_train)
test_length = len(Y_test)


In [7]:
print("train length: {0}, test length: {1}".format(train_length, test_length))
print("x_train length: {0}, x_test length: {1}".format(len(X_train), len(X_test)))
print(index_dict[train_length - 1])
print(index_dict[train_length])

train length: 23186, test length: 11420
x_train length: 23186, x_test length: 11420
[661]
[661]


In [8]:
train_maze_count = index_dict[train_length][0]
def Adjust_Train_test_Lengths():
  if index_dict[train_length-1][0] == index_dict[train_length][0]:
    for i in range(test_length):
      if index_dict[train_length + i][0] == train_maze_count:
        element = X_test.pop(0)
        X_train.append(element)
        element = Y_test.pop(0)
        Y_train.append(element)
      else:
        break

Adjust_Train_test_Lengths()
X_train_position = position_dict[0:len(X_train)]
X_test_position = position_dict[len(X_train):data_count]
X_PS_train = X_PS[0:len(X_train)]
X_PS_test = X_PS[len(X_train):data_count]

train_length = len(Y_train)
test_length = len(Y_test)
train_maze_count = index_dict[train_length-1][0]
maze_count = index_dict[data_count-1][0]
test_maze_count = maze_count - train_maze_count

In [9]:
print('after')
print("total maze count: {0}, train maze count: {1}, test maze count: {2}".format(maze_count, train_maze_count, test_maze_count))
print("x_train length: {0}, x_test length: {1}".format(len(X_train), len(X_test)))
#print(X_train[train_length - 1])
print(X_test[0])
print(X_test[1])
print(index_dict[train_length - 1])
print(index_dict[train_length])

after
total maze count: 1000, train maze count: 661, test maze count: 339
x_train length: 23200, x_test length: 11406
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[661]
[662]


In [10]:
train_in_position = np.reshape(X_train_position, (-1, 1*2, ))
test_in_position = np.reshape(X_test_position, (-1, 1*2, ))

train_in_X_PS = np.reshape(X_PS_train, (-1, gridSize, gridSize))
test_in_X_PS = np.reshape(X_PS_test, (-1, gridSize, gridSize))

train_in_X = np.reshape(X_train, (-1, gridSize, gridSize))
test_in_X = np.reshape(X_test, (-1, gridSize, gridSize))

train_out = tf.keras.utils.to_categorical( Y_train, 4 )
test_out = tf.keras.utils.to_categorical( Y_test, 4 )

In [11]:
grid_input = tf.keras.layers.Input( shape = (gridSize,gridSize) )
grid_input_PS = tf.keras.layers.Input( shape = (gridSize,gridSize) )
position_input = tf.keras.layers.Input(shape = (1*2, ))

flatten_grid = tf.keras.layers.Flatten()(grid_input)
flatten_grid_PS = tf.keras.layers.Flatten()(grid_input_PS)
concat = tf.keras.layers.concatenate([flatten_grid, flatten_grid_PS, position_input])
dense_1 = tf.keras.layers.Dense( units = 200, activation = tf.nn.relu )( concat )
dense_2 = tf.keras.layers.Dense( units = 100, activation = tf.nn.relu )( dense_1 )
dense_3 = tf.keras.layers.Dense( units = 50, activation = tf.nn.relu )( dense_2 )
dense_4 = tf.keras.layers.Dense( units = 25, activation = tf.nn.relu )( dense_3 )
actions_output = tf.keras.layers.Dense( units = 4, activation = None )( dense_4 )
probabilities = tf.keras.layers.Softmax()( actions_output )

model = tf.keras.Model( inputs = [grid_input, grid_input_PS, position_input], outputs = probabilities )
model.compile( optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'] )

In [12]:
def directionFromAction(action, position):
  direction = ()
  if action == 0:
    # towards right
    direction = (0 + position[0], 1 + position[1])
  elif action == 1: 
    # towards down
    direction = (1 + position[0], 0 + position[1])
  elif action == 2:
    # towards up
    direction = (-1 + position[0], 0 + position[1])
  elif action == 3:
  # towards left
    direction = (0 + position[0], -1 + position[1])
  
  return direction

def generate_confusion_matrix(data, labels):
  mat = [[ 0 for i in range(4)] for j in range(4)]

  predictions = np.argmax( model.predict(data), axis = 1 )

  for i in range(data[0].shape[0]):
    mat[ labels[i] ][ predictions[i] ] += 1
    #if i>=0 and i<= 30:
      #print(predictions[i])

  for i in range(4):
    print( "\t".join( [ str(c) for c in mat[i] ] ) )

  return mat

def AccuracyFrom_ConfusionMatrix(confusion_output):
  correct = 0
  incorrect = 0

  for i in range(4):
    for j in range(4):
      if i==j:
        correct += confusion_output[i][j]
      else:
        incorrect += confusion_output[i][j]

  accuracy = correct/(correct+incorrect)
  return accuracy


In [13]:
confusion_output = generate_confusion_matrix([test_in_X, test_in_X_PS, test_in_position], Y_test)
accuracy = AccuracyFrom_ConfusionMatrix(confusion_output)
print(accuracy)


23	259	1419	3900
14	158	826	3257
3	8	71	248
7	54	238	921
0.10284061020515518


In [14]:
history = model.fit([train_in_X, train_in_X_PS, train_in_position], train_out, epochs = 15)

Epoch 1/15
725/725 [==============================] - 3s 3ms/step - loss: 0.9750 - accuracy: 0.5659
Epoch 2/15
725/725 [==============================] - 2s 3ms/step - loss: 0.7652 - accuracy: 0.6627
Epoch 3/15
725/725 [==============================] - 2s 3ms/step - loss: 0.5933 - accuracy: 0.7465
Epoch 4/15
725/725 [==============================] - 2s 3ms/step - loss: 0.4968 - accuracy: 0.7869
Epoch 5/15
725/725 [==============================] - 2s 3ms/step - loss: 0.4350 - accuracy: 0.8134
Epoch 6/15
725/725 [==============================] - 2s 3ms/step - loss: 0.3877 - accuracy: 0.8353
Epoch 7/15
725/725 [==============================] - 2s 3ms/step - loss: 0.3470 - accuracy: 0.8542
Epoch 8/15
725/725 [==============================] - 2s 3ms/step - loss: 0.3188 - accuracy: 0.8634
Epoch 9/15
725/725 [==============================] - 2s 3ms/step - loss: 0.2989 - accuracy: 0.8712
Epoch 10/15
725/725 [==============================] - 2s 3ms/step - loss: 0.2871 - accuracy: 0.8800

In [15]:
confusion_output = generate_confusion_matrix([test_in_X, test_in_X_PS, test_in_position], Y_test)
accuracy = AccuracyFrom_ConfusionMatrix(confusion_output)

print(accuracy)


5121	409	33	38
343	3637	31	244
34	40	128	128
16	310	101	793
0.8485884622128704


In [16]:
model.save('model_agent3_dim10_1000.hf5')
#model_file = ''
#model=load_model(model_file)
#model.summary()

INFO:tensorflow:Assets written to: model_agent3_dim10_1000.hf5/assets


In [17]:
model=load_model('model_agent3_dim10_1000.hf5')
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 10, 10)]     0           []                               
                                                                                                  
 input_2 (InputLayer)           [(None, 10, 10)]     0           []                               
                                                                                                  
 flatten (Flatten)              (None, 100)          0           ['input_1[0][0]']                
                                                                                                  
 flatten_1 (Flatten)            (None, 100)          0           ['input_2[0][0]']                
                                                                                              

In [18]:
directions = [[0,1], [1, 0], [-1, 0], [0, -1]]

neighbours_in_8_directions = [[0, 1], # towards East
                                 [1, 0],  # towards south
                                 [-1, 0], # towards north
                                 [0, -1], # towards west
                                 [1, 1],  # towards SE
                                 [-1, 1], # towards NE
                                 [-1, -1],# towards NW
                                 [1, -1]] # towards SW

def Update_blocked_NeighborsIn_8_Directions(maze,kg_PS,pos):
  #neighbourNodes = []
  if kg_PS[pos[0]][pos[1]] == -1:
    blocked = 0
    for newPosition in neighbours_in_8_directions:
    # Get the position of the node in maze
        nodeLocation = (pos[0] + newPosition[0], pos[1] + newPosition[1])

        #Check if the node position is within the maze dimensions
        if CheckValidPosition(nodeLocation) and maze[nodeLocation[0]][nodeLocation[1]] == 1:
          #neighbourNodes.append(nodeLocation)
          blocked += 1

    kg_PS[pos[0]][pos[1]] = blocked
  return kg_PS
  
def getUpdatedPos(kg, pos):
  positions = []
  for i in directions:
    new_position = [pos[0] + i[0], pos[1] + i[1]]
    #if new_position[0] >= 0 and new_position[0] < gridSize and new_position[1] >= 0 and new_position[1] < gridSize:
    if CheckValidPosition(new_position):
      if kg[new_position[0]][new_position[1]] != 1:
        positions.append(new_position)

  rand = np.random.randint(len(positions))     
  pos[0] = positions[rand][0]
  pos[1] = positions[rand][1]
  return pos


def CheckValidPosition(position):
  if position[0] >= 0 and position[0] < gridSize and position[1] >= 0 and position[1] < gridSize:
    return True
  else:
    return False


In [24]:
def FindPathInTestGrids():
  initial_grid = [[0 for i in range(gridSize)] for j in range(gridSize)]
  initial_grid_PS = [[-1 for i in range(gridSize)] for j in range(gridSize)]
  #initial_grid[0][0] = 0
  #initial_grid[gridSize-1][gridSize-1] = 0
  initial_position = np.array([[0, 0]]) #test_in_position[0:1]
  pathLengths = []
  TimeTaken = []
  solved_grids = 0
  unsolved_grids = 0

  for i in range (train_maze_count+1, maze_count+1):
  #for i in range (train_maze_count+1, maze_count+1):
    pathFound = False
    grid_number = i
    pathlength = 0
    time_One_grid =0
    kg =  np.array([initial_grid])
    kg_PS = np.array([initial_grid_PS])
    pos = np.array([[0, 0]])
    maze = maze_dict[i -1]
    #print(maze)
    #print(kg)
    pos = np.array([[0, 0]])
    #print(pos)
    startTime = time.time()  # Start time 
    blockcount = 0

    while pathFound == False:
      #print(kg[0])
      #print(pos)
      #kg[0] = UpdateKg(maze, kg[0], pos[0])
      kg_PS[0] = Update_blocked_NeighborsIn_8_Directions(maze, kg_PS[0], pos[0])
      #print(kg[0])
      pathlength += 1
      #break
      single_prediction = np.argmax(model.predict([kg, kg_PS, pos]), axis = 1)
      direction = directionFromAction(single_prediction,pos[0])
      #print(direction)
      if direction == (gridSize-1, gridSize-1):
        pathFound = True
        pathLengths.append(pathlength)
        endTime = time.time() #end time
        time_One_grid = endTime - startTime
        TimeTaken.append(time_One_grid)
        solved_grids += 1
        #print(pathlength)
        #print(time_One_grid)
        print('grid {0} solved'.format(solved_grids))
        break
      isDirectionValid = CheckValidPosition(direction)
      if (isDirectionValid and maze[direction[0]][direction[1]] == 1) or (isDirectionValid == False):
        #print('blocked')
        if isDirectionValid:
          kg[0][direction[0]][direction[1]] = maze[direction[0]][direction[1]]
        pathlength += 1
        pos[0] = getUpdatedPos(maze, pos[0])
        #print(pos)
        blockcount +=1
        if blockcount > (gridSize*5):
          print('limit excceeded')
          unsolved_grids += 1
          break
      else:
        #print('not blocked')
        kg[0][pos[0][0]][pos[0][1]] = maze[pos[0][0]][pos[0][1]]
        pos[0] = direction

  return test_maze_count, pathLengths, TimeTaken, solved_grids, unsolved_grids
 

In [25]:
test_maze_count, pathLengths, TimeTaken, solved_grids, unsolved_grids = FindPathInTestGrids()
print('test grids: {0}'.format(test_maze_count))
print('path lengths : {0}'.format(pathLengths))
print('Time taken: {0} '.format(TimeTaken))
print('solved grids: {0}, unsolved grids : {1}'.format(solved_grids, unsolved_grids))
#print(AstartTime_dict[train_maze_count: maze_count])

KeyboardInterrupt: ignored

In [22]:
sovability = solved_grids/(solved_grids + unsolved_grids)
avg_path_length = sum(pathLengths)/len(pathLengths)
avg_time = sum(TimeTaken)/len(TimeTaken)
print("solvability : {0} ".format(sovability))
print("average path length : {0} ".format(avg_path_length))
print("average time taken to solve : {0} ".format(avg_time))

solvability : 0.625 
average path length : 42.8 
average time taken to solve : 1.8244924068450927 
