In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from collections import defaultdict
import pickle
from sklearn.model_selection import train_test_split
import time
from numpy.core.records import array
from keras.models import load_model

In [3]:
with open('/content/grids_agent1_dim10_count1000.pkl', "rb") as f:
    dict = pickle.load(f)

X = dict['KnowledgeGrid']
Y = dict['action']
position_dict = dict['position']
index_dict = dict['Index']
data_count = len(Y)
gridSize = len(X[0][0])
maze_dict = dict['maze']
AstartTime_dict = dict['AstarTime']

In [ ]:
# Reshape position list into array
for i in range(data_count):
  position_dict[i] = np.reshape(position_dict[i], 1*2)

In [4]:
print(gridSize)
print(data_count)
print(X[0])
print(position_dict[0])
print(len(maze_dict))
print((maze_dict[0]))
print((AstartTime_dict[0]))
print(len(AstartTime_dict))
print((AstartTime_dict))
print(X[0].shape[0])

10
26821
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
(0, 0)
1000
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 1, 0], [0, 0, 0, 1, 0, 1, 0, 0, 0, 1], [0, 0, 0, 0, 1, 1, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 0, 1, 0, 0, 0, 0, 1], [0, 0, 1, 1, 0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]]
0.0011715888977050781
1000
[0.0011715888977050781, 0.0010848045349121094, 0.0, 0.0010716915130615234, 0.0009708404541015625, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0010004043579101562, 0.0010001659393310547, 0.0, 0.0, 0.0, 0.0009999275207519531, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0010004043579101562, 0.0, 0.0, 0.0010876655578613281, 0.0009999275207519531, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0010039806365966797, 0.0010173320770263672

Add position to knowledge grid

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, shuffle=False)
train_length = len(Y_train)
test_length = len(Y_test)


In [6]:
print("train length: {0}, test length: {1}".format(train_length, test_length))
print("x_train length: {0}, x_test length: {1}".format(len(X_train), len(X_test)))
print(index_dict[train_length - 1])
print(index_dict[train_length])

train length: 17970, test length: 8851
x_train length: 17970, x_test length: 8851
[670]
[670]


In [7]:
train_maze_count = index_dict[train_length][0]
def Adjust_Train_test_Lengths():
  if index_dict[train_length-1][0] == index_dict[train_length][0]:
    for i in range(test_length):
      if index_dict[train_length + i][0] == train_maze_count:
        element = X_test.pop(0)
        X_train.append(element)
        element = Y_test.pop(0)
        Y_train.append(element)
      else:
        break

Adjust_Train_test_Lengths()
X_train_position = position_dict[0:len(X_train)]
X_test_position = position_dict[len(X_train):data_count]

train_length = len(Y_train)
test_length = len(Y_test)
train_maze_count = index_dict[train_length-1][0]
maze_count = index_dict[data_count-1][0]
test_maze_count = maze_count - train_maze_count

In [8]:
print('after')
print("total maze count: {0}, train maze count: {1}, test maze count: {2}".format(maze_count, train_maze_count, test_maze_count))
print("x_train length: {0}, x_test length: {1}".format(len(X_train), len(X_test)))
print(X_test[0])
print(X_test[1])
print(index_dict[train_length - 1])
print(index_dict[train_length])

after
total maze count: 1000, train maze count: 670, test maze count: 330
x_train length: 17980, x_test length: 8841
[[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[670]
[671]


In [9]:
train_in_position = np.reshape(X_train_position, (-1, 1*2, ))
test_in_position = np.reshape(X_test_position, (-1, 1*2, ))
train_in = np.reshape(X_train, (-1, gridSize, gridSize))
test_in = np.reshape(X_test, (-1, gridSize, gridSize))
train_out = tf.keras.utils.to_categorical( Y_train, 4 )
test_out = tf.keras.utils.to_categorical( Y_test, 4 )

In [17]:
grid_input = tf.keras.layers.Input( shape = (gridSize,gridSize, 1) )
cnn_1 = tf.keras.layers.Conv2D( filters = 64, kernel_size = (3,3), strides = (1,1), padding = "valid", activation = tf.nn.relu )( grid_input )
flatten_grid = tf.keras.layers.Flatten()(cnn_1)
position_input = tf.keras.layers.Input(shape = (1*2, ))
concat = tf.keras.layers.concatenate([flatten_grid, position_input])
dense_1 = tf.keras.layers.Dense( units = 200, activation = tf.nn.relu )( concat )
dense_2 = tf.keras.layers.Dense( units = 100, activation = tf.nn.relu )( dense_1 )
dense_3 = tf.keras.layers.Dense( units = 50, activation = tf.nn.relu )( dense_2 )
dense_4 = tf.keras.layers.Dense( units = 25, activation = tf.nn.relu )( dense_3 )
actions_output = tf.keras.layers.Dense( units = 4, activation = None )( dense_4 )
probabilities = tf.keras.layers.Softmax()( actions_output )

model = tf.keras.Model( inputs = [grid_input, position_input], outputs = probabilities )
model.compile( optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'] )

In [18]:
def directionFromAction(action, position):
  direction = ()
  if action == 0:
    # towards right
    direction = (0 + position[0], 1 + position[1])
  elif action == 1: 
    # towards down
    direction = (1 + position[0], 0 + position[1])
  elif action == 2:
    # towards up
    direction = (-1 + position[0], 0 + position[1])
  elif action == 3:
  # towards left
    direction = (0 + position[0], -1 + position[1])
  
  return direction

def generate_confusion_matrix(data, labels):
  mat = [[ 0 for i in range(4)] for j in range(4)]

  predictions = np.argmax( model.predict(data), axis = 1 )

  for i in range(data[0].shape[0]):
    mat[ labels[i] ][ predictions[i] ] += 1
    #if i>=0 and i<= 30:
      #print(predictions[i])

  for i in range(4):
    print( "\t".join( [ str(c) for c in mat[i] ] ) )

  return mat

def AccuracyFrom_ConfusionMatrix(confusion_output):
  correct = 0
  incorrect = 0

  for i in range(4):
    for j in range(4):
      if i==j:
        correct += confusion_output[i][j]
      else:
        incorrect += confusion_output[i][j]

  accuracy = correct/(correct+incorrect)
  return accuracy


In [19]:
confusion_output = generate_confusion_matrix([test_in, test_in_position], Y_test)
accuracy = AccuracyFrom_ConfusionMatrix(confusion_output)
print(accuracy)


533	6	3882	62
170	12	3365	3
1	0	122	0
19	0	661	5
0.07600950118764846


In [20]:
history = model.fit([train_in, train_in_position], train_out, epochs = 15)

Epoch 1/15
562/562 [==============================] - 7s 12ms/step - loss: 0.7866 - accuracy: 0.6830
Epoch 2/15
562/562 [==============================] - 7s 12ms/step - loss: 0.5974 - accuracy: 0.7431
Epoch 3/15
562/562 [==============================] - 7s 12ms/step - loss: 0.5023 - accuracy: 0.7735
Epoch 4/15
562/562 [==============================] - 7s 12ms/step - loss: 0.4685 - accuracy: 0.7831
Epoch 5/15
562/562 [==============================] - 7s 12ms/step - loss: 0.4219 - accuracy: 0.7961
Epoch 6/15
562/562 [==============================] - 6s 11ms/step - loss: 0.3951 - accuracy: 0.8002
Epoch 7/15
562/562 [==============================] - 7s 12ms/step - loss: 0.3699 - accuracy: 0.8103
Epoch 8/15
562/562 [==============================] - 6s 12ms/step - loss: 0.3604 - accuracy: 0.8110
Epoch 9/15
562/562 [==============================] - 7s 12ms/step - loss: 0.3454 - accuracy: 0.8181
Epoch 10/15
562/562 [==============================] - 6s 11ms/step - loss: 0.3305 - accura

In [16]:
confusion_output = generate_confusion_matrix([test_in, test_in_position], Y_test)
accuracy = AccuracyFrom_ConfusionMatrix(confusion_output)

print(accuracy)

4262	161	2	58
734	2642	1	173
26	30	2	65
54	358	0	273
0.8120122158126909


In [ ]:
model.save('model_agent1_0_dim10_15000.hf5')
#model_file = ''
#model=load_model(model_file)
#model.summary()

INFO:tensorflow:Assets written to: model_agent1_0_dim10_15000.hf5/assets


In [ ]:
model=load_model('model_agent1_0_dim10_1000.hf5')
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_5 (InputLayer)           [(None, 10, 10)]     0           []                               
                                                                                                  
 flatten_2 (Flatten)            (None, 100)          0           ['input_5[0][0]']                
                                                                                                  
 input_6 (InputLayer)           [(None, 2)]          0           []                               
                                                                                                  
 concatenate_2 (Concatenate)    (None, 102)          0           ['flatten_2[0][0]',              
                                                                  'input_6[0][0]']          

In [21]:
directions = [[0,1], [1, 0], [-1, 0], [0, -1]]

def UpdateKg(maze, kg, pos):
  for i in directions:
    new_position = [pos[0] + i[0], pos[1] + i[1]]
    #print(new_position)
    #print(kg[new_position[0]][new_position[1]])
    #print(maze[new_position[0]][new_position[1]])
    if new_position[0] >= 0 and new_position[0] < gridSize and new_position[1] >= 0 and new_position[1] < gridSize:
      kg[new_position[0]][new_position[1]] = maze[new_position[0]][new_position[1]]
      #print('updated')
  return kg 

  
def getUpdatedPos(kg, pos):
  positions = []
  for i in directions:
    new_position = [pos[0] + i[0], pos[1] + i[1]]
    #if new_position[0] >= 0 and new_position[0] < gridSize and new_position[1] >= 0 and new_position[1] < gridSize:
    if CheckValidPosition(new_position):
      if kg[new_position[0]][new_position[1]] != 1:
        positions.append(new_position)

  rand = np.random.randint(len(positions))     
  pos[0] = positions[rand][0]
  pos[1] = positions[rand][1]
  return pos


def CheckValidPosition(position):
  if position[0] >= 0 and position[0] < gridSize and position[1] >= 0 and position[1] < gridSize:
    return True
  else:
    return False


In [28]:
def FindPathInTestGrids():
  initial_grid = [[0 for i in range(gridSize)] for j in range(gridSize)]#test_in[0:1]
  #initial_grid[0][0] = 0
  #initial_grid[gridSize-1][gridSize-1] = 0
  initial_position = np.array([[0, 0]]) #test_in_position[0:1]
  pathLengths = []
  TimeTaken = []
  solved_grids = 0
  unsolved_grids = 0

  #for i in range (train_maze_count+10, train_maze_count+35):
  for i in range (train_maze_count+1, maze_count+1):
    pathFound = False
    grid_number = i
    pathlength = 0
    time_One_grid =0
    kg =  np.array([initial_grid])
    pos = np.array([[0, 0]])
    maze = maze_dict[i -1]
    #print(maze)
    #print(kg)
    pos = np.array([[0, 0]])
    #print(pos)
    startTime = time.time()  # Start time 
    blockcount = 0

    while pathFound == False:
      #print(kg[0])
      #print(pos)
      kg[0] = UpdateKg(maze, kg[0], pos[0])
      #print(kg[0])
      pathlength += 1
      #break
      single_prediction = np.argmax(model.predict([kg,pos]), axis = 1)
      direction = directionFromAction(single_prediction,pos[0])
      #print(direction)
      if direction == (gridSize-1, gridSize-1):
        pathFound = True
        pathLengths.append(pathlength)
        endTime = time.time() #end time
        time_One_grid = endTime - startTime
        TimeTaken.append(time_One_grid)
        solved_grids += 1
        #print(pathlength)
        #print(time_One_grid)
        print('grid {0} solved'.format(solved_grids))
        break
      isDirectionValid = CheckValidPosition(direction)
      if (isDirectionValid and maze[direction[0]][direction[1]] == 1) or (isDirectionValid == False):
        #print('blocked')
        pathlength += 1
        pos[0] = getUpdatedPos(kg[0], pos[0])
        #print(pos)
        blockcount +=1
        if blockcount > gridSize * 5:
          print('limit excceeded')
          unsolved_grids += 1
          break
      else:
        #print('not blocked')
        pos[0] = direction

  return test_maze_count, pathLengths, TimeTaken, solved_grids, unsolved_grids
 

In [29]:
test_maze_count, pathLengths, TimeTaken, solved_grids, unsolved_grids = FindPathInTestGrids()
print('test grids: {0}'.format(test_maze_count))
print('path lengths : {0}'.format(pathLengths))
print('Time taken: {0} '.format(TimeTaken))
print('solved grids: {0}, unsolved grids : {1}'.format(solved_grids, unsolved_grids))
#print(AstartTime_dict[train_maze_count: maze_count])

grid 1 solved
limit excceeded
grid 2 solved
grid 3 solved
grid 4 solved
grid 5 solved
grid 6 solved
grid 7 solved
grid 8 solved
grid 9 solved
grid 10 solved
grid 11 solved
grid 12 solved
limit excceeded
grid 13 solved
grid 14 solved
grid 15 solved
grid 16 solved
grid 17 solved
grid 18 solved
grid 19 solved
grid 20 solved
grid 21 solved
grid 22 solved
grid 23 solved
grid 24 solved
grid 25 solved
grid 26 solved
grid 27 solved
grid 28 solved
grid 29 solved
grid 30 solved
grid 31 solved
grid 32 solved
grid 33 solved
limit excceeded
grid 34 solved
limit excceeded
grid 35 solved
grid 36 solved
grid 37 solved
grid 38 solved
grid 39 solved
grid 40 solved
grid 41 solved
limit excceeded
grid 42 solved
grid 43 solved
grid 44 solved
grid 45 solved
grid 46 solved
grid 47 solved
grid 48 solved
grid 49 solved
grid 50 solved
grid 51 solved
grid 52 solved
grid 53 solved
grid 54 solved
grid 55 solved
grid 56 solved
grid 57 solved
grid 58 solved
grid 59 solved
grid 60 solved
limit excceeded
grid 61 solve

In [30]:
sovability = solved_grids/(solved_grids + unsolved_grids)
avg_path_length = sum(pathLengths)/len(pathLengths)
avg_time = sum(TimeTaken)/len(TimeTaken)
print("solvability : {0} ".format(sovability))
print("average path length : {0} ".format(avg_path_length))
print("average time taken to solve : {0} ".format(avg_time))

solvability : 0.9151515151515152 
average path length : 35.36092715231788 
average time taken to solve : 1.616810350228619 
